### ISSUE TITLE
Proper config file

### ISSUE THREAD

**Issue by zeydabadi** [cbedetti/Dcm2Bids#12]
Hi ...
I'm still struggling with getting to run the Dcm2bids but assuming that I can run it what would be a proper config file for this type of data that attached here? I tried to modify the config file (copied below) but not sure if I'm doing this correctly.

Thank you!
Mahmoud

"descriptions": [
        {
            "dataType": "anat",
            "suffix": "T1w",
            "criteria": {
                "in": {"SeriesDescription": "T1W_3D"}
            }
        },
        {
            "dataType": "anat",
            "suffix": "T2w",
            "criteria": {
                "in": {"SeriesDescription": "T2w_SPC"},
                "equal": {"EchoTime": 0.563}
            }
        },
        {
            "dataType": "dwi",
            "suffix": "dwi",
			"customLabels": "b2000-PA",
            "criteria": {
                "in": {"SeriesDescription": "dMRI_b2000_dir90_PA"}
            }
        },
		{
            "dataType": "dwi",
            "suffix": "SB",
			"customLabels": "b2000-PA",
            "criteria": {
                "in": {"SeriesDescription": "dMRI_b2000_dir90_PA_SBRef"}
            }
        },
		{
            "dataType": "dwi",
            "suffix": "dwi",
			"customLabels": "b700-AP",
            "criteria": {
                "in": {"SeriesDescription": "dMRI_b700_dir89_AP"}
            }
        },
		{
            "dataType": "dwi",
            "suffix": "SB",
			"customLabels": "b700-AP",
            "criteria": {
                "in": {"SeriesDescription": "dMRI_b700_dir89_AP_SBRef"}
            }
        },
        {
            "dataType": "func",
            "suffix": "bold",
            "customLabels": "rest-AP",
            "criteria": {
                "equal": {"SeriesDescription": "rfMRI_REST_AP"}
            }
        },
		{
            "dataType": "func",
            "suffix": "SB",
			"customLabels": "AP",
            "criteria": {
                "equal": {"SeriesDescription": "rfMRI_REST_AP_SBRef"}
            }
        },
		{
            "dataType": "func",
            "suffix": "bold",
            "customLabels": "rest-PA",
            "criteria": {
                "equal": {"SeriesDescription": "rfMRI_REST_PA"}
            }
        },
		{
            "dataType": "func",
            "suffix": "SB",
			"customLabels": "PA",
            "criteria": {
                "equal": {"SeriesDescription": "rfMRI_REST_PA_SBRef"}
            }
        }
    ]

![dataset](https://user-images.githubusercontent.com/16503138/30171401-e512edb0-93bf-11e7-8653-097556ba1e7d.png)

**Comment by cbedetti** [comment]
The setup of the configuration file should be easier now with the pattern concept.
Unfortunately, it is not backward compatible but there is a README now !
