### ISSUE TITLE
Usage example

### ISSUE THREAD

**Issue by zeydabadi** [cbedetti/Dcm2Bids#13]
Can someone please give me an example of dcm2bids command line usage?
It is not clear to me how I should use it.
- what is [-h]?

- what should be after -d? what is DICOM_DIR? Is it the directory that contains *.IMA files? what if I have only access to the *.DCM files?

- what should be after -p? what does PARTICIPANT mean? should it be the subject ID(s)?

-what is a SESSION? what if not all subjects have the same number of the sessions?

-what is   [--clobber]?

I really appreciate if you could give me an actual example that clarifies my questions.
Thank you for your time!

Mahmoud

**Comment by cbedetti** [comment]
The README update should answer your questions.
Also, the setup of the configuration file should be easier now with the pattern concept.
Unfortunately, it is not backward compatible but there is a README now !
