### ISSUE TITLE
Where to type the command?

### ISSUE THREAD

**Issue by takua624** [cbedetti/Dcm2Bids#14]
Hi, 

this problem might be a silly one, but I don't know where to type the command like "dcm2bids -d sourcedata/s101/DICOM/ -s S101 -c code/config_dcm2bids.json".

I'm using Windows7, and the cmd doesn't accept this command.

**Comment by cbedetti** [comment]
Hi,
dcm2bids is a command line tool so it's from the command prompt.
Also, dcm2bids was not tested on any Windows OS.

**Comment by takua624** [comment]
Thank you. No wonder I can't use it.

But eventually I use python scripts to call the functions directly, thanks!
