### ISSUE TITLE
Questions on file configurations

### ISSUE THREAD

**Issue by shaomingwang** [cbedetti/Dcm2Bids#15]
Hi!

I have a question regarding how to configure my (original) DICOM files for the function to read. I tried the dcm2bids_helper function on one of my participants data (one run) to derive an example configuration file but it says "No handlers could be found for logger "dcm2bids". Any hint would be helpful!

Thanks!

**Comment by cbedetti** [comment]
Hi,
Thanks for reporting this issue.
Could you paste the whole error and the version of your OS and python ?

**Comment by shaomingwang** [comment]
Hi,
I tried to use dcm2bids_helper to derive example of configuration files, but I get:
"No handlers could be found for logger "dcm2bids""
Essentially, I wonder if there's an example showing how my DICOM file folder should look like.

Thanks!

**Comment by kdestasio** [comment]
I have encountered the same error.

**OS:**
MacOS Sierra
version 10.12.6

**Error:**
```
~/Desktop/temp/Dcm2Bids $ dcm2bids_helper -d /Users/username/Desktop/REV001_20150406/
No handlers could be found for logger "dcm2bids"
Example in:
/Users/username/Desktop/temp/Dcm2Bids/tmp_dcm2bids/dcm2niix-example
```

```
python --version
Python 2.7.10
```

The dcm2niix-example directory is empty.

I am trying to determine a solution and will post an update if I do.

**Comment by kdestasio** [comment]
This appears to be 2 separate issues (for me at least). One of which I'm posting the solution to here (which permits creation of the dcm2bids_helper output) and one that I am still working on related to the absence of the log files (to which the "No handlers..." message relates).

(1) For me, what is called before the `dcm2bids_helper` errors out is the wrapper for dcm2niix, which is expected to live in `/usr/bin/`. The solution to this was to: 
- remove dcm2Bids from my computer
- install `dcm2niix` **on the system**, following the instructions on the `dcm2niix` repo, which are:
```
mkdir build && cd build
cmake ..
make install
```
- do a clean install of `dcm2Bids`, following the instructions on this repo:
```
git clone https://github.com/cbedetti/Dcm2Bids
cd Dcm2Bids
python setup.py install
```

(2) The logging isn't quite set up. There's some unknown conflict such that output log files are not created to alert the user to the above issue. The inability to produce the log generates the message `No handlers could be found for logger "dcm2bids"`.

**Comment by cbedetti** [comment]
Hi,
For now, I have disable the logger for dcm2bids_helper. This should fix this issue.
Two changes:
- the output is now `tmp_dcm2bids/helper`
- it's better to install with `pip install .` I have updated the readme.
Thanks
