### ISSUE TITLE
-p argument question

### ISSUE THREAD

**Issue by Islast** [cbedetti/Dcm2Bids#16]
Hi!
In the [usage example in your readme](https://github.com/cbedetti/Dcm2Bids#usage) you omit the -p argument. When I try to do this I get the following:  
`dcm2bids: error: the following arguments are required: -p/--participant`  
What does the -p argument do and how should I use it?

**Comment by cbedetti** [comment]
You're right. I'll change that in the example.
Fot the explanation of the `-p` argument, it is in the readme. It is the code of your participant.

```
  -p PARTICIPANT, --participant PARTICIPANT
                        Participant code
```

**Comment by Islast** [comment]
Can I get it to do all particpants at once?

**Comment by cbedetti** [comment]
Right now, `dcm2bids` works one session at a time. One session is all the acquisitions between the entry and exit of the participant in the scanner.
Doing several sessions is on the todo list !

The code is the name of the participant in bids. Ex: `sub-<code>`
Is it more clear ?

**Comment by Islast** [comment]
Yep, that all makes sense now! I'll just reiterate to check that I've understood:
 I should be running dcm2bids on a directory containing a single session and telling it the participant and session number to record a la bids format.

**Comment by cbedetti** [comment]
Yes, it's exactly that. I've update the readme. Let me know if it's more clear.
Feel free to correct my english, it's not my native language.

**Comment by Islast** [comment]
Great :sparkles:. I checked out the changes you made to the README, it's clear to me :+1: 

As a newbie who's installed and used this tool, I have a couple of ideas for additions to the README that might help first time users- how would you feel about me making a pull request?

**Comment by cbedetti** [comment]
Yes, very good idea.
It could be a tutorial.
