### ISSUE TITLE
Exists Docker or Singularity Image of Dcm2Bids?

### ISSUE THREAD

**Issue by kdestasio** [cbedetti/Dcm2Bids#17]
Is there a container anywhere for Dcm2Bids so that it can be run on HPCs where the user may not have write access to the python libraries?

**Comment by cbedetti** [comment]
I've added a singularity-hub link.
Let me know if it works.

**Comment by kdestasio** [comment]
Thank you for creating the singularity container!

If you have time to spend on this, I have a couple questions about it. I've pulled the image and am attempting to use it. Do you have an example of the command you would use to run dcm2bids with the container? For example, do you use a script in the HPC environment that calls the container, and if so, what would that look like? Or run the command inside the container? And how do you point to the config file if you run inside the container, given that only root users can write files/directories?

Thank you!

**Comment by kdestasio** [comment]
Never mind. I ran it by binding the needed directories and shelling into the container:

```
singularity shell -B /data/directory/ -B /code/directory-with-config/ Dcm2Bids-master.simg
``` 
and then executing the command within the container.

```
dcm2bids -d /path/to/DICOMS/ -o /path/to/output/ -s <session> -c /path/to/config.json -p <sub-id>
```

There may be a better way, but this works.

**Comment by cbedetti** [comment]
`singularity run Dcm2Bids-master.simg -d /path/to/DICOMS/ -o /path/to/output/ -s <session> -c /path/to/config.json -p <sub-id>`
This should work without binding ?

**Comment by kdestasio** [comment]
I had thought so as well, but I get the following error when I attempt to use `singularity run`:

```
[user@talapas-ln1]$ singularity run Dcm2Bids-master.simg -d /path/to/DICOMS/ -o /path/to/output/ -s wave1 -c /path/to/config.json -p 110
Traceback (most recent call last):
  File "/usr/local/bin/dcm2bids", line 87, in <module>
    sys.exit(main())
  File "/usr/local/bin/dcm2bids", line 82, in main
    app = Dcm2bids(**vars(args))
  File "/usr/local/lib/python2.7/dist-packages/dcm2bids/dcm2bids.py", line 31, in __init__
    self.config = load_json(config)
  File "/usr/local/lib/python2.7/dist-packages/dcm2bids/utils.py", line 11, in load_json
    with open(filename, 'r') as f:
IOError: [Errno 2] No such file or directory: '/path/to/config.json'

[user@talapas-ln1]$ ls /path/to/config.json 
/path/to/config.json
```

I suspect this is because the DICOM directory and the directory with the config file are not among the bind points specified by the container image (e.g. they are not root and they are not in my home directory).  When the run script is executed, it's from within the container and so can't access the config file that exists outside the container.

**Comment by kdestasio** [comment]
Using `run` does work if you also bind the directories. 

e.g. 
`singularity run -B /path/to/DICOMS -B /path/to/output Dcm2Bids-master.simg -d /path/to/DICOMS/ -o /path/to/output/ -s <session> -c /path/to/config.json -p <sub-id>`

I made some wrapper scripts so the dcm2bids helper can be easily used via singularity container on an HPC and so dcm2bids can be easily batched on an HPC using the singularity container. It's a work in progress, and I'm by no means a great coder, but if it's of any use, you and others are welcome to build from it.

Scripts here: https://github.com/UOSAN/REV_scripts/tree/master/org/dcm2bids

Documentation here: https://uosanlab.atlassian.net/wiki/spaces/SW/pages/44269646/Convert+DICOM+to+BIDS
