### ISSUE TITLE
Config File

### ISSUE THREAD

**Issue by anandpreshob** [cbedetti/Dcm2Bids#18]
Hi ,
Trying to design a config files with heuristics. Are there any resources where there are already existing config files or will you be able to help us design one. If you are willing to share your's that would be great too.
Thanks for you time

**Comment by cbedetti** [comment]
Hi,
Right now, there's this [example](https://github.com/cbedetti/Dcm2Bids/blob/master/example/config.json) and the explanation in the README.
It's very likely your scanner data will differ from this example so you'll need to edit the criteria.

**Comment by Islast** [comment]
@anandpreshob This is the explanation I gave to my colleague re our work using the Dcm2Bids tool on our pilot dwi data, including another (rather crude) example config file (right at the end). In our case these were the only dcm files present so the criteria dictionary is not specific. The explanation is a little wordy, but I hope it helps


---
The config file tells dcm2bids how to group and label acquisitions.
Referring to the example used in https://github.com/cbedetti/Dcm2Bids#configuration-file
```json
{
    "descriptions": [
        {
            "dataType": "anat",
            "modalityLabel": "T2w",
            "criteria": {
                "SeriesDescription": "*T2*",
                "EchoTime": 0.1
            }
        },
        {
            "dataType": "func",
            "modalityLabel": "bold",
            "customLabels": "task-rest",
            "criteria": {
                "SidecarFilename": "006*"
            }
        }
    ]
}
```
This config file tells us how to group acquisitions and how to label them. In this example we're collecting files containing 
```json
       "SeriesDescription": "*T2*",
       "EchoTime": 0.1
```
in their dcm2niix sidecars[<sup>1</sup>] and describing them as `anat`, `T2w` type images. Then we group files with sidecars<sup>1</sup> beginning "006" and describe them as `func`, `bold` type images with the `customLabel` "task-rest"

### Modality labels and custom labels

`modalityLabel` is a mandatory field describing the modality of the acquisition. Having this in the filename is a [BIDS specification](http://bids.neuroimaging.io/bids_spec1.0.2.pdf#page=12) requirement for `anat` and `func` data. for `dwi` data you can pass `"modalityLabel":"dwi"`

`customLabel` is an optional field you can use to add information to the new file filenames, e.g `customLabel: "task-rest"` tells dcm2bids that all files with sidecars<sup>1</sup> beginning "006" are "task-rest" files and to label them as such. 

### <sup>1</sup>: sidecars
For each acquisition, dcm2niix creates an associated .json file, containing information from the dicom header. These are known as __sidecars__. dcm2bids uses these sidecars to filter the groups of acquisitions. dcm2bids allows specification of acquisition groups by sidecar contents, or/and by sidecar filenames.
You probably need to look at your sidecars to define this filtering, you can generate all the sidecars (along with everything else) for an individual participant using dcm2bids_helper (https://github.com/cbedetti/Dcm2Bids#tools).

# Our images
I think the images we're looking at right now all go in the same group, so we don't need to tell dcm2bids much about our sidecars. We do need to tell it our `dataType`("dwi"), `modalityLabel` (dwi images seem not to have these, see [BIDS specification](http://bids.neuroimaging.io/bids_spec1.0.2.pdf#page=22); referring to the longer [example config file](https://github.com/cbedetti/Dcm2Bids/blob/b4f473b3a3741f838ef403ee510999db23f096ca/example/config.json) in the dcm2bids repo it seems like we pass modalityLabel:"dwi") and any required `customLabels` (none to my knowledge, but possibly should say pilot, need to check BIDS spec).

```json
{
    "descriptions": [
        {
            "dataType": "dwi",
            "modalityLabel": "dwi",
            "criteria": {
                "SidecarFilename": "*"
            }
        }
    ]
}
```

**Comment by anandpreshob** [comment]
Hi All,
Thank you for the comments, is there any way to give a range to the echo time, let's say
`
 "SeriesDescription": "*T2*",
 "EchoTime":  > 0.1
`

**Comment by cbedetti** [comment]
You can do this kind of criteria using Regex from 2.0.0 on
I'll open an issue to add example in the documentation
