### ISSUE TITLE
Configuration File for Field Mapping Data

### ISSUE THREAD

**Issue by dlevitas** [cbedetti/Dcm2Bids#21]
Hello,

I'm putting together a configuration file for running dcm2bids; however, I'm unsure how to format the field mapping portion. The field mapping data consists of two spin echoes with opposite phase directions. Essentially, I don't know what I need to put in the configuration file for the "modalityLabel" and "criteria" sections.

Thanks.

**Comment by gladomat** [comment]
Here's what I use but I have two magnitude images and a phase difference:
```
        {
            "dataType": "fmap",
            "modalityLabel": "magnitude",
            "criteria": {
                "SidecarFilename": "*010*fieldmap1*"
            }
        },
        {
            "dataType": "fmap",
            "modalityLabel": "phasediff",
            "criteria": {
                "SidecarFilename": "*011*fieldmap1*"
            }
        },
```

**Comment by neurolabusc** [comment]
@gladomat it sounds like you have a field map, e.g. for use with FUGUE. I think @dlevitas is using two acquisitions with reversed phase encoding directions, e.g. for use with TOPUP. If you have modern Siemens data, the phase encoding should be encoded in the PhaseEncodingDirection BIDS tag, e.g. `"PhaseEncodingDirection": "j-"`.  However, this information is not available for data from other vendors. At our center, we make the phase encoding explicit when we set up the protocol name on the scanner, e.g. so we will have "fMRI_ap" and "fMRI_pa" to distinguish anterior-posterior phase encoding. In this case, the this should be reported in the SidecarFilename (as long as dcm2niix was called with protocol name inserted in the filename -f %p) as well as in the BIDS ProtocolName tag, e.g. `"ProtocolName": "fMRI_ap"`.

**Comment by dlevitas** [comment]
I had forgotten about this, but wanted to post my solution before closing. For spin echo field maps, they should follow a format like this in the configuration file:
```
{
         "dataType": "fmap",
         "modalityLabel": "epi",
         "IntendedFor": [
            4,
            6,
            8,
            10,
            12,
            14,
            16,
            18
         ],
         "criteria": {
            "SidecarFilename": "004*"
         }
      },
      {
         "dataType": "fmap",
         "modalityLabel": "epi",
         "IntendedFor": [
            4,
            6,
            8,
            10,
            12,
            14,
            16,
            18
         ],
         "criteria": {
            "SidecarFilename": "005*"
         }
      },
```

I have also come across field maps where there are two magnitudes and one phase difference. In these cases, the portion of the configuration file for the field maps is something like this:

```
{
         "dataType": "fmap",
         "modalityLabel": "magnitude1",
         "IntendedFor": [
            9,
            10,
            11
         ],
         "criteria": {
            "SidecarFilename": "011*",
            "EchoTime": 0.00492
         }
      },
      {
         "dataType": "fmap",
         "modalityLabel": "magnitude2",
         "IntendedFor": [
            9,
            10,
            11
         ],
         "criteria": {
            "SidecarFilename": "011*",
            "EchoTime": 0.00738
         }
      },
      {
         "dataType": "fmap",
         "modalityLabel": "phasediff",
         "IntendedFor": [
            9,
            10,
            11
         ],
         "criteria": {
            "SidecarFilename": "012*"
         },
         "sidecarChanges": {
            "EchoTime1": 0.00492,
            "EchoTime2": 0.00738
         }
      },
```

It should be noted that these examples require the most recent software versions of dcm2bids (2.1.4) and dcm2niix (v1.0.20190410).
