### ISSUE TITLE
How to deal with the data which have 1 json and 2 nii.gz

### ISSUE THREAD

**Issue by Ayumu722** [cbedetti/Dcm2Bids#23]
Hi ,

Thank you for making this toolbox and I like this toolbox!
But, I faced a problem while using various type of data sets.
There is a fieldmap data which have 1 json and 2 nii.gz in Philips data.
e.g.)
Fieldmap4.92testCLEAR4.2_19770703150928_ph.json
Fieldmap4.92testCLEAR4.2_19770703150928_ph_1.nii.gz
Fieldmap4.92testCLEAR4.2_19770703150928_ph_2.nii.gz

In this case, dcm2bids could only pick and change name the json data only.
The other two nii.gz are in the  tmp_dcm2bids folder.

My question is
How to deal with this kind of data?

Thanks for you time

**Comment by cbedetti** [comment]
This should be good in 2.0.0
