### ISSUE TITLE
Make "dicom_dir" parameter also a string instead of only a list

### ISSUE THREAD

**Issue by pwitkow** [cbedetti/Dcm2Bids#24]
Hi, 

I'm having two problems and I'm not sure if they are related. I'm running the package through python using the simplest syntax as a test:

`from dcm2bids import dcm2bids

dcms=dcm2bids.dcm2bids(dicom_dir='mydir', participant='subj', config='myconfig', output_dir='outdir')
dcms.run()

`
When I call the run method it first searches sub-strings of the DICOM directory. For example, if the directory is 'jd56', it returns:

Unable to find DICOM images in j
Unable to find DICOM images in d
Unable to find DICOM images in 5
Unable to find DICOM images in 6

Then it continuously prints the following: "Problem reading ECAT7 file!"

I'm using python v3.5, with dcm2bids v1.1.8 on a linux server.  

Any help would be much appreciated!

**Comment by neurolabusc** [comment]
Try running from command line with very latest dcm2niix code. It fixes an issue with some ecat files.

**Comment by neurolabusc** [comment]
To be clear, make sure your version of dcm2niix includes the commit described here
  https://github.com/rordenlab/dcm2niix/issues/183
that may explain the ECAT7 error - and the ECAT errors are now a bit more descriptive. I am not sure why 'jd56' are assumed to be four different folders, and that may be a dcm2bids issue. In any case, running from the command line should clarify that...

**Comment by pwitkow** [comment]
I ran it from the command line with dcm2niix 1.0.20171215 and it seems to have worked just fine. Is there no fix for this to run it through python, though?

**Comment by cbedetti** [comment]
That's because the parameter `dicom_dir` is a list. The information is added in the docstring now.
Running with the script `dcm2bids` take care of that.

One solution could be to check the type of `dicom_dir` and handle `str` and `list`.
