### ISSUE TITLE
Method for dealing with multi-echo acquisitions

### ISSUE THREAD

**Issue by Islast** [cbedetti/Dcm2Bids#26]
When I run dcm2bids on multi-echo acquisitions I end up with each echo recorded as a separate run. [Bids specification](http://bids.neuroimaging.io/bids_spec.pdf#page=14) asks for echoes within the same acquisition to have the same name except for echo number.
Does dcm2bids have a method for handling multi-echo images?

**Comment by cbedetti** [comment]
Writing a description for eah echo adding a different `customLabels` should do the trick
