### ISSUE TITLE
How to reorganize T1_FLAIR, T2_FLAIR,T1,T2 into anat folder

### ISSUE THREAD

**Issue by Danni222** [cbedetti/Dcm2Bids#33]
I have some 'T2_FLAIR' nifti files. Since 'T2_FLAIR' matches both 'T2w' and 'FLAIR',  according to dcm2bids documentation, sidecars with more than one matching descriptions are kept in dcm2bids_data directory. But if I want to put this file into BIDS anat folder, does dcm2bids provides this feature?

**Comment by neurolabusc** [comment]
A `T2_FLAIR` should be labeled `FLAIR` in the [BIDS](https://bids.neuroimaging.io/bids_spec.pdf) specification. In T1-weighted scans fluid (CSF) is intrinsically dark. In T2-weighted images fluid is intrinsically bright unless a precise inversion time is used to knock out the fluid signal. The resulting image is sometimes referred to as "T2 FLAIR", "FLAIR" or (if you use Siemens) "dark fluid". In BIDS, T2 refers to a conventional T2 image and FLAIR refers to a T2-FLAIR. The contrast of a FLAIR image is different than T2, so processing such as normalization with an intra-modal cost function will fail if the FLAIR is treated like a T2.
