### ISSUE TITLE
Tips for using anonymiser option

### ISSUE THREAD

**Issue by hstojic** [cbedetti/Dcm2Bids#38]
Hi there,

do you have any tips on anonymiser tools that would play well with dcm2bids?

e.g., I'm looking at Poldrack lab utility [here](https://github.com/poldracklab/pydeface), but not sure it conforms the requirements. Perhaps it can be wrapped in a shell script to fit the bill, perhaps somebody has an example to share?

Hrvoje

**Comment by jooh** [comment]
Pydeface can be called as a script, so that should work. When you pip install it you will end up with a 'pydeface' CLI.

Let me know if that works - I originally developed the anonymiser feature to work with pydeface, but it looks like they may have refactored the code a bit since last time I used it.

**Comment by hstojic** [comment]
I tried with pydeface, both directly put as an option in `dcm2bids` call, and wrapped in a following simple script:
```bash
#!/bin/bash
pydeface --outfile $2 --verbose $1
```
I also made sure its executable. I get an error, that the output file from the subprocess call cannot be found and dcm2bids stops execution.

**Comment by jooh** [comment]
You shouldn't need a shell script wrapper. Pydeface is a command line application. Try putting in the absolute path to pydeface instead of just the name. It might not be on path in the session you're running python in.

**Comment by hstojic** [comment]
Ok, it was a path issue, of different sort, thanks for the help. 

Though, supply pydeface directly as an argument `-a /home/hstojic/.pyenv/nipy/bin/pydeface` does not work. I get the following error:
```python
INFO:dcm2bids:subprocess:  /home/hstojic/.pyenv/nipy/bin/pydeface /media/hstojic/dataneuro/fnclearning_fmri/dBids/tmp_dcm2bids/sub-s087/002_20190128.MQ05073_FIL_MPRAGE_64ch_Head_20190128184304.nii.gz /media/hstojic/dataneuro/fnclearning_fmri/dBids/sub-s087/anat/sub-s087_T1w.nii.gz
INFO:dcm2bids:
usage: pydeface [-h] [--outfile path] [--force] [--applyto  [...]]
                [--cost mutualinfo] [--template path] [--facemask path]
                [--nocleanup] [--verbose]
                path
pydeface: error: unrecognized arguments: /media/hstojic/dataneuro/fnclearning_fmri/dBids/sub-s087/anat/sub-s087_T1w.nii.gz
------------
pydeface 2.0
------------
```
I think this is because new version of pydeface accepts a single argument, additional flags are needed for output file. Wrapping it in a shell script as in my previous comment works.

**Comment by jooh** [comment]
Ah, got it. Thanks for looking into this.

**Comment by cbedetti** [comment]
Thanks for reporting this.
It's now possible to add the option `defaceTpl` in the configuration file.

For this version of pydeface : `"defaceTpl": "pydeface -outfile {dstFile} {srcFile}"`
