### ISSUE TITLE
Issue with multiple sessions 

### ISSUE THREAD

**Issue by Nialljb** [cbedetti/Dcm2Bids#41]
Hello, 

This seems like a great tool, but I am having difficultly running it with subjects that have multiple sessions. In the output directory for each subject it adds scans from each previous session as an additional run in the current session. 

It could be me but I don't think I'm doing anything silly in a for loop. When executed the session & subject are explicitly included. In the tmp_dcm2bids dir the sessions are labeled correctly but then there seems to be a problem moving it across into the main structure. 

Is this a general issue or am I being dense?

**Comment by cbedetti** [comment]
Do you have some example of your code ?
Executing `dcm2bids -h` could maybe help you

**Comment by Nialljb** [comment]
Thank you. I don't think I kept a version of that script. I just made my own bash function since I couldn't figure out what I was doing wrong and not that savvy with Python. 
Best,

**Comment by cbedetti** [comment]
Great.
One of the goals is to offer the possibility to the user to not code complex heuristic. The use of the script should be enough.
However, you must build the configuration file for your study at least.
Best,
