### ISSUE TITLE
Optional -m flag

### ISSUE THREAD

**Issue by sportnoah14** [cbedetti/Dcm2Bids#49]
Hi,

First, thanks for creating this. I'm a regular user and it helps a lot. I work with MR and CT images so I need to use dcm2niix flag -m for the CT images. Is there any chance this can be an optional argument? Again, thank you for creating this.

**Comment by cbedetti** [comment]
Yes, it's possible.

See dcm2niixOptions here :  https://cbedetti.github.io/Dcm2Bids/advance/

Let me know if the documentation is not clear.
