### ISSUE TITLE
parser error 

### ISSUE THREAD

**Issue by ajdneuro** [cbedetti/Dcm2Bids#8]
Hi Christophe,

Thanks so much for this tool. I am running into an error when trying to convert my mprage to bids. My json (as txt file) is attached and my command is: dcm2bids -d sub1 -p 001 -c sub1_mprage_5e_20140427134518_13.json 

I get the following error: raceback (most recent call last):
  File "/usr/local/dcm2bids/07.19.2017/scripts/dcm2bids", line 61, in <module>
    sys.exit(main())
  File "/usr/local/dcm2bids/07.19.2017/scripts/dcm2bids", line 57, in main
    return app.run()
  File "/usr/local/dcm2bids/07.19.2017/dcm2bids/dcm2bids.py", line 35, in run
    parser = Sidecarparser(dcm2niix.sidecars, self.config["descriptions"])
KeyError: 'descriptions'

Thanks very much for your help!

Best,
Alex

[sub1_mprage_5e_20140427134518_13.txt](https://github.com/cbedetti/Dcm2Bids/files/1178195/sub1_mprage_5e_20140427134518_13.txt)

**Comment by egarza** [comment]
Can you send your configure.json file? I think the problem should be there.

**Comment by jooh** [comment]
You are missing the 'descriptions' field. Try adding the following to the top of your json:

`
{
    "descriptions": [`

and at the end

`
    ]
}
`

**Comment by cbedetti** [comment]
Thank you all.
The setup of the configuration file should be easier now with the pattern concept.
Unfortunately, it is not backward compatible but there is a README now !
